name:
  Run tests
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true
      - name: Setup python
        continue-on-error: true
        uses: actions/setup-python@v4
      - name: Install dependencies
        continue-on-error: true
        run: |
          pip install -r requirements.txt
          echo "Dependencies had been installed"
      - name: Install pytest
        continue-on-error: true
        run: pip install pytest
      - name: Run tests
        continue-on-error: true
        run: |
          pytest tests.py
          echo -e "\e[1;32mAll tests had been passed\e[0m"
        
