name:
  Run tests
on:
  push:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: true
      - name: Setup python
        continue-on-error: true
        uses: actions/setup-python@v4
      - name: Install dependencies
        continue-on-error: true
        run: |
          pip install -r requirements.txt
          echo -e "\e[1;32mDependencies have been installed\e[0m"
      - name: Install pytest
        continue-on-error: true
        run: |
          pip install pytest
          echo -e "\e[1;32mPytest was succesfully installed\e[0m"
      - name: Run tests
        continue-on-error: true
        run: |
          pytest tests.py
          echo -e "\e[1;32mAll tests have been passed!\e[0m"
        
